baseURL = "https://markushylleberg.github.io/docs"
languageCode = "en-us"
title = "Urban Rigger"
theme = "blank"
publishDir = "docs"


[[menu.main]]
name               	= "Home"
titel               = "Home"
weight             	= -201
identifier         	= "home"
url                	= "/test3"


[[menu.main]]
name               	= "Projects"
titel               = "Projects"
weight             	= -201
identifier         	= "projects"
url                	= "/test3/projects"

[[menu.main]]
name               	= "View container"
titel               = "View container"
weight             	= -101
identifier         	= "view"
url                	= "/test3/view"


[[menu.main]]
name               	= "Sustainbility"
titel               = "Sustainbility"
weight             	= -101
identifier         	= "sustan"
url                	= "/test3/sustan"

[[menu.main]]
name               	= "About us"
titel               = "About us"
weight             	= -101
identifier         	= "aboutus"
url                	= "/test3/aboutus"

[[menu.main]]
name               	= "Contact"
titel               = "Contact"
weight             	= -101
identifier         	= "contact"
url                	= "/test3/contact"

[[menu.main]]
name               	= "Students"
titel               = "Students"
weight             	= -101
identifier         	= "students"
url                	= "/test3/students"